export const MILLISECOND = 1;
export const SECOND = 1000 * MILLISECOND;
export const MINUTE = 60 * SECOND;
export const HOUR = 60 * MINUTE;
export const DAY = 24 * HOUR;
export const WEEK = 7 * DAY;
export const MONTH = 30 * DAY; // estimate
export const YEAR = 365 * DAY; // estimate
export const X400YEARS = 146097 * DAY; // exact
export const X4YEARS = 365 * DAY * 4 + 1 * DAY; // estimate
